version: '3.8'

networks:
  monitoring:
    driver: bridge
    
volumes:
  prometheus_data: {}

services:
  mysql:
    image: mysql
    container_name: mysql_mem
    restart: always
    volumes:
      - ./data:/data
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - 3306:3306
    networks:
      - monitoring

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - monitoring

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter_mem
    restart: unless-stopped
    volumes:
      - ./.my.cnf:/home/.my.cnf
    command:
      - '--collect.binlog_size'
      - '--collect.perf_schema.eventsstatements'
    ports:
      - 9104:9104
    networks:
      - monitoring
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_mem
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring